try:
    result = 45/0
except:
    print("Error Happent")
finally:
    print('Done')